### ISSUE TITLE
XDMA Driver Configuration, Possible issue

### ISSUE THREAD

**Issue by Nakul1048** [CMU-SAFARI/DRAM-Bender#6]
When following the Row Hammer example provided at this link on youtube
https://www.youtube.com/watch?v=FklVEsfdZCI

we are running into an issue where the number of bit flips does not match the values it should be. For example when we do sudo ./ps10, it gives the same value as sudo ./ps100, sudo ./ps1000, sudo ./ps10000 etc.

we are using the xdma driver that came with the github repo but when we use xilinx's latest XDMA driver we get this issue.

1017: ADDI r10 r10 1
1018: BL PC:627 r10 r11 (TARGET LABEL: READ_BEGIN)
1019: END
ps: ../../api/board.cpp:128: int BoardInterface::xdma_recv(void*, uint): Assertion `count <= size' failed.
Aborted

can you let us know what might be wrong?

I have also attached out code file to this error and also a photo of out vivado program output 
[DRAMBENDERCODE.txt](https://github.com/CMU-SAFARI/DRAM-Bender/files/12874623/DRAMBENDERCODE.txt)

[ProgramOutput.txt](https://github.com/CMU-SAFARI/DRAM-Bender/files/12874633/ProgramOutput.txt)

**Comment by olgunataberk** [comment]
This happens when data sent from DRAM Bender logic is not received by the user via a platform.readData() call. Forcefully killing a DRAM Bender program or miscalculating the amount of READs that are issued to DRAM is often the case when this happens. When a DRAM Bender program is executed afterwards, the XDMA driver responds with more data than expected to the DRAM Bender program. 

A temporary solution is to run the executable under sources/apps/ResetBoard/ as sudo ./SoftMC_reset, this will reset DRAM Bender logic and also the XDMA driver's state.

We added the above explanation to the FAQ in the README.

I also remember there was something wrong with line 160 in the program you shared (that we wrote in the tutorial). It might be wise to compute the number of bitflips in a way you are sure is correct.
